# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magiclaw_msg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12magiclaw_msg.proto\x12\x08MagiClaw\"E\n\x04\x43law\x12\r\n\x05\x61ngle\x18\x01 \x01(\x02\x12\r\n\x05speed\x18\x02 \x01(\x02\x12\n\n\x02iq\x18\x03 \x01(\x02\x12\x13\n\x0btemperature\x18\x04 \x01(\x05\"@\n\x06\x46inger\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\x0c\n\x04pose\x18\x02 \x03(\x02\x12\r\n\x05\x66orce\x18\x03 \x03(\x02\x12\x0c\n\x04node\x18\x04 \x03(\x02\"f\n\x05Phone\x12\x11\n\tcolor_img\x18\x01 \x01(\x0c\x12\x11\n\tdepth_img\x18\x02 \x03(\x05\x12\x13\n\x0b\x64\x65pth_width\x18\x03 \x01(\x05\x12\x14\n\x0c\x64\x65pth_height\x18\x04 \x01(\x05\x12\x0c\n\x04pose\x18\x05 \x03(\x02\"\xa3\x01\n\x08MagiClaw\x12\x11\n\ttimestamp\x18\x01 \x01(\x02\x12\x1c\n\x04\x63law\x18\x02 \x01(\x0b\x32\x0e.MagiClaw.Claw\x12\"\n\x08\x66inger_0\x18\x03 \x01(\x0b\x32\x10.MagiClaw.Finger\x12\"\n\x08\x66inger_1\x18\x04 \x01(\x0b\x32\x10.MagiClaw.Finger\x12\x1e\n\x05phone\x18\x05 \x01(\x0b\x32\x0f.MagiClaw.Phoneb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magiclaw_msg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLAW._serialized_start=32
  _CLAW._serialized_end=101
  _FINGER._serialized_start=103
  _FINGER._serialized_end=167
  _PHONE._serialized_start=169
  _PHONE._serialized_end=271
  _MAGICLAW._serialized_start=274
  _MAGICLAW._serialized_end=437
# @@protoc_insertion_point(module_scope)
